#pragma config(Sensor, in2,    mogoLift,       sensorPotentiometer)
#pragma config(Sensor, dgtl3,  leftDrive,      sensorQuadEncoder)
#pragma config(Sensor, dgtl11, rightDrive,     sensorQuadEncoder)
#pragma config(Motor,  port2,           mogoLeft,      tmotorNone, openLoop)
#pragma config(Motor,  port3,           mogoRight,     tmotorNone, openLoop)
#pragma config(Motor,  port4,           driveFrontLeft, tmotorNone, openLoop)
#pragma config(Motor,  port5,           driveFrontRight, tmotorNone, openLoop)
#pragma config(Motor,  port6,           driveBackLeftA, tmotorNone, openLoop)
#pragma config(Motor,  port7,           driveBackRightA, tmotorNone, openLoop)
#pragma config(Motor,  port8,           driveBackLeftB, tmotorNone, openLoop)
#pragma config(Motor,  port9,           driveBackRightB, tmotorNone, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**
 * main.c - Entry point for our codebase
 * The structure of the project is as follows:
 *
 * lib/
 *   hal.c - Hardware Abstraction Layer
 *   lcd.c - LCD Library
 *   motor.c - Motor Algorithmns
 *   pid.c - General purpose PID (Super simple, basically just makes the calculation)
 *   rerun.c - Contains code for the rerun system
 * routines/
 *   auton.c - Routines for the 15-second autonomous
 *   skills.c - Routines for the 60-second programming skills
 *
 **/

#pragma platform(VEX2)
#pragma competitionControl(Competition)
#include "Vex_Competition_Includes.c"

#include "routines\auton.c"
#include "routines\skills.c"

#include "lib\rerun.c"
#include "lib\hal.c"
#include "lib\lcd.c"

void pre_auton() {
  bStopTasksBetweenModes = false;
  lcdStartup();
  robotConfigure();
  // startTask(handleAll);
}

task autonomous() {
  if (match.type == 0) {
    goAuton(match.routine);
  } else if (match.type == 2) {
    goSkills(match.routine);
  }
}


task usercontrol() {
  while (true) {

    updateState();

    if (match.type == 3) {
      outputStateCode();
    }

    wait1Msec(20);
  }
}
